### ISSUE TITLE
Add integrations tests

### ISSUE THREAD

**Issue by sivaprasadreddy** [testcontainers/jooq-testcontainers-codegen-maven-plugin#4]
The plugin can be tested using https://github.com/khmarbaise/maven-it-extension.
Implement tests to verify the successful code generation with all the supporting databases.

**Comment by romchellis** [comment]
Hi @sivaprasadreddy 
I've discovered suggested library and found it quite complex for usage.
Also it doesn't work actually, it always brings JOOQ compiler errors due to the discrepancy between the real structure of the project and the emulation.
Please take a look on [my Pull Request](https://github.com/testcontainers/jooq-testcontainers-codegen-maven-plugin), i achieved it much more simpler way using `maven-plugin-testing-harness`
